### ISSUE TITLE
The italic style is invalid with Chinese

### ISSUE THREAD

**Issue by Duan-Wuya** [pengx17/logseq-dev-theme#13]
Dev theme is an awesome theme. But I find the italic style is invalid with Chinese, iike this:

![image](https://user-images.githubusercontent.com/59379633/140492213-161cd7fb-2209-452a-b4be-f604dd8367db.png)

Could you please fix this? Thx a lot!

**Comment by pengx17** [comment]
@Duan-Wuya Italic is rarely used for Chinese characters because the fonts are skewed programmable and being known as "伪斜体". Most Latin fonts do come with a second set of italic fonts which come under the same name but with different glyphs. So I recommend not setting italic styles for texts in Chinese.

With that being said, I have pushed a fix for this... LOL
