### ISSUE TITLE
[Dark] Block Reference style

### ISSUE THREAD

**Issue by Bad3r** [pengx17/logseq-dev-theme#25]
Block references background color doesn't blend well with the theme

![](https://user-images.githubusercontent.com/25513724/147363348-e6ca632c-406d-4f48-94b3-5aad70c6d950.png)

**Comment by pengx17** [comment]
@Bad3r
<img width="324" alt="Screen Shot 2021-12-26 at 5 14 14 PM" src="https://user-images.githubusercontent.com/584378/147403864-ffb2afc1-825a-4192-97f9-c8842cf0a1ca.png">
it looks fine to me on Mac 🤔. I think the block ref background may not need to be that outstanding though, but I am not an expert on coloring & theming. Do you have a suggestion about how to make it blend in a better way?

**Comment by Bad3r** [comment]
I think it's very outstanding. I find it somewhat distracting when it's in the middle of a text block, specially when compared to a page link, e.g. `[[logseq]]`

![](https://user-images.githubusercontent.com/25513724/147412881-8154f434-215b-403a-b046-28146727025c.png)

Also, there seems to be an extra space at the end of a block ref. 

A possible solution is to remove the background color completely and change the text color similar to how page links are handled, or use the default logseq style and modify the underline color to `#313942` (left sidebar color) or `#92b8d7` (page link color).  
 

I am also not sure about the `#` symbol in the start. I think the logseq default theme handles this better with just adding an underline with a different color.

![](https://user-images.githubusercontent.com/25513724/147412968-fcaf64fd-e351-4865-9cf4-23d039a83ffc.png)

**Comment by pengx17** [comment]
@Bad3r oh, I get what you mean. The block reference style was made like this was because this theme was originally forked from https://github.com/PiotrSss/logseq-clean-themes, including the `#` sign and background. I have not thought about the issue back then, but now I believe you are right: having the two may disrupt the reading experience.

IMO the way you suggested that using different colors may not apply well to distinguish between block/page references. Alternatively, I propose to use dotted underlines for block references, and leave what it is for block ref, like this:  

![image](https://user-images.githubusercontent.com/584378/147413829-fcf958af-ad94-422b-ae38-575dea344bec.png)

What do you think?

**Comment by Bad3r** [comment]
That's a great solution! I like the look of the dotted line more.

I am not sure about using this color for the dotted line. Maybe consider using the same color used for page links but for the dotted line or a different shade of blue (example: `#a3cef1`)

**Comment by pengx17** [comment]
I am releasing a new version based on our discussion here.

**Comment by Bad3r** [comment]
Awesome! Thank you! 🚀
